export const flux2FlexSchema = {
	type: "object",
	title: "Input",
	required: ["prompt"],
	properties: {
		prompt: { type: "string", title: "Prompt" },
		input_images: {
			type: "array",
			title: "Input Images",
			description: "Reference images for image-to-image generation.",
		},
		aspect_ratio: {
			type: "string",
			title: "Aspect Ratio",
			enum: [
				"match_input_image",
				"custom",
				"1:1",
				"16:9",
				"3:2",
				"2:3",
				"4:5",
				"5:4",
				"9:16",
				"3:4",
				"4:3",
			],
			default: "1:1",
		},
		resolution: {
			type: "string",
			title: "Resolution",
			enum: ["match_input_image", "0.5 MP", "1 MP", "2 MP", "4 MP"],
			default: "1 MP",
		},
		width: {
			type: "integer",
			title: "Width",
			minimum: 256,
			maximum: 2048,
		},
		height: {
			type: "integer",
			title: "Height",
			minimum: 256,
			maximum: 2048,
		},
		steps: {
			type: "integer",
			title: "Steps",
			default: 30,
			minimum: 1,
			maximum: 50,
		},
		guidance: {
			type: "number",
			title: "Guidance",
			default: 4.5,
			minimum: 1.5,
			maximum: 10,
		},
		output_format: {
			type: "string",
			title: "Output Format",
			enum: ["webp", "png", "jpg"],
			default: "webp",
		},
		output_quality: {
			type: "integer",
			title: "Output Quality",
			default: 80,
			minimum: 1,
			maximum: 100,
		},
		prompt_upsampling: {
			type: "boolean",
			title: "Prompt Upsampling",
			default: true,
		},
		safety_tolerance: {
			type: "integer",
			title: "Safety Tolerance",
			default: 2,
			minimum: 1,
			maximum: 5,
		},
	},
} as const;
