/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/onboarding'
import { Route as AuthLibraryRouteImport } from './routes/_auth/library'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthLibraryIndexRouteImport } from './routes/_auth/library/index'
import { Route as AuthProjectsNewRouteImport } from './routes/_auth/projects/new'
import { Route as AuthProjectsProjectIdRouteImport } from './routes/_auth/projects/$projectId'
import { Route as AuthLibraryLocationsRouteImport } from './routes/_auth/library/locations'
import { Route as AuthLibraryCharactersRouteImport } from './routes/_auth/library/characters'
import { Route as AuthProjectsProjectIdIndexRouteImport } from './routes/_auth/projects/$projectId.index'
import { Route as AuthProjectsProjectIdReferencesRouteImport } from './routes/_auth/projects/$projectId.references'
import { Route as AuthProjectsProjectIdEditorRouteImport } from './routes/_auth/projects/$projectId.editor'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SignInRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLibraryRoute = AuthLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLibraryIndexRoute = AuthLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLibraryRoute,
} as any)
const AuthProjectsNewRoute = AuthProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLibraryLocationsRoute = AuthLibraryLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthLibraryRoute,
} as any)
const AuthLibraryCharactersRoute = AuthLibraryCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AuthLibraryRoute,
} as any)
const AuthProjectsProjectIdIndexRoute =
  AuthProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdReferencesRoute =
  AuthProjectsProjectIdReferencesRouteImport.update({
    id: '/references',
    path: '/references',
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)
const AuthProjectsProjectIdEditorRoute =
  AuthProjectsProjectIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/library': typeof AuthLibraryRouteWithChildren
  '/onboarding': typeof AuthOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/library/characters': typeof AuthLibraryCharactersRoute
  '/library/locations': typeof AuthLibraryLocationsRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRouteWithChildren
  '/projects/new': typeof AuthProjectsNewRoute
  '/library/': typeof AuthLibraryIndexRoute
  '/projects/$projectId/editor': typeof AuthProjectsProjectIdEditorRoute
  '/projects/$projectId/references': typeof AuthProjectsProjectIdReferencesRoute
  '/projects/$projectId/': typeof AuthProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/onboarding': typeof AuthOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/library/characters': typeof AuthLibraryCharactersRoute
  '/library/locations': typeof AuthLibraryLocationsRoute
  '/projects/new': typeof AuthProjectsNewRoute
  '/library': typeof AuthLibraryIndexRoute
  '/projects/$projectId/editor': typeof AuthProjectsProjectIdEditorRoute
  '/projects/$projectId/references': typeof AuthProjectsProjectIdReferencesRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/library': typeof AuthLibraryRouteWithChildren
  '/_auth/onboarding': typeof AuthOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_auth/library/characters': typeof AuthLibraryCharactersRoute
  '/_auth/library/locations': typeof AuthLibraryLocationsRoute
  '/_auth/projects/$projectId': typeof AuthProjectsProjectIdRouteWithChildren
  '/_auth/projects/new': typeof AuthProjectsNewRoute
  '/_auth/library/': typeof AuthLibraryIndexRoute
  '/_auth/projects/$projectId/editor': typeof AuthProjectsProjectIdEditorRoute
  '/_auth/projects/$projectId/references': typeof AuthProjectsProjectIdReferencesRoute
  '/_auth/projects/$projectId/': typeof AuthProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/dashboard'
    | '/library'
    | '/onboarding'
    | '/sign-in/$'
    | '/library/characters'
    | '/library/locations'
    | '/projects/$projectId'
    | '/projects/new'
    | '/library/'
    | '/projects/$projectId/editor'
    | '/projects/$projectId/references'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in/$'
    | '/library/characters'
    | '/library/locations'
    | '/projects/new'
    | '/library'
    | '/projects/$projectId/editor'
    | '/projects/$projectId/references'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/sign-in'
    | '/_auth/dashboard'
    | '/_auth/library'
    | '/_auth/onboarding'
    | '/sign-in/$'
    | '/_auth/library/characters'
    | '/_auth/library/locations'
    | '/_auth/projects/$projectId'
    | '/_auth/projects/new'
    | '/_auth/library/'
    | '/_auth/projects/$projectId/editor'
    | '/_auth/projects/$projectId/references'
    | '/_auth/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof SignInRoute
    }
    '/_auth/onboarding': {
      id: '/_auth/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/library': {
      id: '/_auth/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthLibraryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/library/': {
      id: '/_auth/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthLibraryIndexRouteImport
      parentRoute: typeof AuthLibraryRoute
    }
    '/_auth/projects/new': {
      id: '/_auth/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthProjectsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId': {
      id: '/_auth/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/library/locations': {
      id: '/_auth/library/locations'
      path: '/locations'
      fullPath: '/library/locations'
      preLoaderRoute: typeof AuthLibraryLocationsRouteImport
      parentRoute: typeof AuthLibraryRoute
    }
    '/_auth/library/characters': {
      id: '/_auth/library/characters'
      path: '/characters'
      fullPath: '/library/characters'
      preLoaderRoute: typeof AuthLibraryCharactersRouteImport
      parentRoute: typeof AuthLibraryRoute
    }
    '/_auth/projects/$projectId/': {
      id: '/_auth/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    '/_auth/projects/$projectId/references': {
      id: '/_auth/projects/$projectId/references'
      path: '/references'
      fullPath: '/projects/$projectId/references'
      preLoaderRoute: typeof AuthProjectsProjectIdReferencesRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
    '/_auth/projects/$projectId/editor': {
      id: '/_auth/projects/$projectId/editor'
      path: '/editor'
      fullPath: '/projects/$projectId/editor'
      preLoaderRoute: typeof AuthProjectsProjectIdEditorRouteImport
      parentRoute: typeof AuthProjectsProjectIdRoute
    }
  }
}

interface AuthLibraryRouteChildren {
  AuthLibraryCharactersRoute: typeof AuthLibraryCharactersRoute
  AuthLibraryLocationsRoute: typeof AuthLibraryLocationsRoute
  AuthLibraryIndexRoute: typeof AuthLibraryIndexRoute
}

const AuthLibraryRouteChildren: AuthLibraryRouteChildren = {
  AuthLibraryCharactersRoute: AuthLibraryCharactersRoute,
  AuthLibraryLocationsRoute: AuthLibraryLocationsRoute,
  AuthLibraryIndexRoute: AuthLibraryIndexRoute,
}

const AuthLibraryRouteWithChildren = AuthLibraryRoute._addFileChildren(
  AuthLibraryRouteChildren,
)

interface AuthProjectsProjectIdRouteChildren {
  AuthProjectsProjectIdEditorRoute: typeof AuthProjectsProjectIdEditorRoute
  AuthProjectsProjectIdReferencesRoute: typeof AuthProjectsProjectIdReferencesRoute
  AuthProjectsProjectIdIndexRoute: typeof AuthProjectsProjectIdIndexRoute
}

const AuthProjectsProjectIdRouteChildren: AuthProjectsProjectIdRouteChildren = {
  AuthProjectsProjectIdEditorRoute: AuthProjectsProjectIdEditorRoute,
  AuthProjectsProjectIdReferencesRoute: AuthProjectsProjectIdReferencesRoute,
  AuthProjectsProjectIdIndexRoute: AuthProjectsProjectIdIndexRoute,
}

const AuthProjectsProjectIdRouteWithChildren =
  AuthProjectsProjectIdRoute._addFileChildren(
    AuthProjectsProjectIdRouteChildren,
  )

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthLibraryRoute: typeof AuthLibraryRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRouteWithChildren
  AuthProjectsNewRoute: typeof AuthProjectsNewRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthLibraryRoute: AuthLibraryRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRouteWithChildren,
  AuthProjectsNewRoute: AuthProjectsNewRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SignInRouteChildren {
  SignInSplatRoute: typeof SignInSplatRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSplatRoute: SignInSplatRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
